### ISSUE TITLE
Humidity conversion times incorrect?

### ISSUE THREAD

**Issue by nseidle** [PaulZC/Qwiic_PHT_MS8607_Library#2]
It looks like you're pulling in TE's library which is good, but I think their humidity [conversion times](https://github.com/TEConnectivity/MS8607_Arduino_Library/blob/master/src/ms8607.cpp#L31) might have a copy and paste error.

Datasheet shows the following:

![image](https://user-images.githubusercontent.com/117102/79003862-bbe10180-7b10-11ea-83e2-d09c2eed6a04.png)

Their pressure conversion times match this table but their humidity times do not. Changing the lib to match these causes the sensor to behave and become much more responsive.

**Comment by nseidle** [comment]
Interestingly their 10x over on all four values.

**Comment by PaulZC** [comment]
Great catch - thank you!
I wonder if this helps explain why the sensor doesn't always .begin cleanly first time?
Fixed in #3.
